title: jtubert.com
email: your-email@example.com
description: Juan Tubert's personal site.
baseurl: ""
url: https://jtubert.com
twitter_username: jtubert
github_username:  jtubert

theme: minima

plugins:
  - jekyll-feed

exclude:
   - ffmpeg.sh
   - script.sh
   - resize-images.sh
   - readme.txt
   - package.json
   - Gemfile
   - Gemfile.lock   
   - Gemfile.local   
   - Gemfile.local.lock   

